### ISSUE TITLE
Import will abort with no message when wrong externalId is set in deployment descriptor

### ISSUE THREAD

**Issue by andrehertwig** [georgwittberger/sfdx-data-deploy-plugin#4]
The Import will break without any error message if _deployConfig.externalIdFieldApiName_ is set with a wrong field which is not an externalId.

Just a little bit irritating :) and cause a long time to search for an error.

Also the _deployConfig.failOnError=false_ does not work in this case.

**Comment by georgwittberger** [comment]
This is caused by missing error handling for the Bulk API job creation. Currently, we do not register any event listener for `error` events which may be emitted by the Bulk API job instance. I'll fix this.

I agree that `failOnError = false` should also allow the deployment to continue in such cases.
